djangoStudy/secondProject/secondProject/urls.py
from django.contrib import admin
from django.urls import path

from app02 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('depart/list/', views.depart_list),
    path('depart/add/', views.depart_add),
    path('depart/delete/', views.depart_delete),
    path('depart/edit/<int:did>/', views.depart_edit),
    path('user/list/', views.user_list),
    path('user/add/', views.user_add),
    path('user/model/form/add/', views.user_model_form_add),
    path('user/edit/<int:uid>/', views.user_edit),
    path('user/delete/<int:uid>/', views.user_delete),
    path('pretty/list/', views.pretty_list),
    path('pretty/add/', views.pretty_add),
    path('pretty/edit/<int:pid>/', views.pretty_edit),
    path('pretty/delete/<int:pid>/', views.pretty_delete),
]

djangoStudy/secondProject/app02/models.py
from django.db import models


# Create your models here.
class Department(models.Model):
    """部门表"""
    title = models.CharField(verbose_name="标题", max_length=32)

    def __str__(self):
        return self.title


class UserInfo(models.Model):
    """员工表"""
    """
        insert into app02_userinfo(name, password, age, account, create_time, gender, department_id) values("韩寒", "123", 24, 100.66, "2020-02-28", 2, 1);
        insert into app02_userinfo(name, password, age, account, create_time, gender, department_id) values("李梅", "123", 43, 100.66, "2020-02-28", 1, 2);
        insert into app02_userinfo(name, password, age, account, create_time, gender, department_id) values("王丫", "123", 12, 100.66, "2020-02-28", 2, 1);
    """
    name = models.CharField(verbose_name="姓名", max_length=16)
    password = models.CharField(verbose_name="密码", max_length=64)
    age = models.IntegerField(verbose_name="年龄")
    # max_digits 数字允许的最大位数，decimal_places 小数的最大位数
    account = models.DecimalField(verbose_name="账户余额", max_digits=10, decimal_places=2, default=0)
    create_time = models.DateField(verbose_name="入职时间")
    # on_delete=models.CASCADE表示级联删除
    department = models.ForeignKey(verbose_name="部门", to='Department', to_field="id", on_delete=models.CASCADE)
    # on_delete=models.SET_NULL表示部门表数据被删除时，这一列数据为空
    # department = models.ForeignKey(to="Department", to_fields="id", null=True, blank=True, on_delete=models.SET_NULL)
    gender_choices = (
        (1, "男"),
        (2, "女")
    )
    # django做的约束,性别只能为男和女
    gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choices)


class PrettyNum(models.Model):
    """
    靓号表
     insert into app02_prettynum(mobile, price, level, status) values("15617822301", 21, 1, 1);
     insert into app02_prettynum(mobile, price, level, status) values("15617822302", 34, 2, 2);
     insert into app02_prettynum(mobile, price, level, status) values("15617822303", 28, 3, 1);
    """
    mobile = models.CharField(verbose_name="手机号", max_length=11)
    price = models.IntegerField(verbose_name="价格", default=0)
    level_choices = (
        (1, "1级"),
        (2, "2级"),
        (3, "3级"),
        (4, "4级"),
    )
    level = models.SmallIntegerField(verbose_name="级别", choices=level_choices, default=1)
    status_choices = (
        (1, "已占用"),
        (2, "未使用"),
    )
    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, default=2)

djangoStudy/secondProject/app02/views.py
from django.shortcuts import render, redirect

from app02 import models
from app02.models import Department, UserInfo, PrettyNum
from django import forms


# Create your views here.
def depart_list(request):
    department_list = Department.objects.all()
    return render(request, 'depart_list.html', {'department_list': department_list})


def depart_add(request):
    if request.method == 'GET':
        return render(request, 'depart_add.html')
    title = request.POST.get("title")
    Department.objects.create(title=title)
    return redirect("/depart/list")


def depart_delete(request):
    did = request.GET.get("did")
    Department.objects.filter(id=did).delete()
    return redirect("/depart/list")


def depart_edit(request, did):
    if request.method == 'GET':
        depart_info = Department.objects.filter(id=did).first()
        return render(request, 'depart_edit.html', {'depart_info': depart_info})
    # did = request.POST.get("id")
    title = request.POST.get("title")
    Department.objects.filter(id=did).update(title=title)
    return redirect("/depart/list")


def user_list(request):
    user_list = UserInfo.objects.all()
    return render(request, 'user_list.html', {'user_list': user_list})


def user_add(request):
    if request.method == 'GET':
        context = {
            'gender_choice': UserInfo.gender_choices,
            'depart_choice': Department.objects.all()
        }
        return render(request, 'user_add.html', context)

    name = request.POST.get('name')
    password = request.POST.get('password')
    age = request.POST.get('age')
    account = request.POST.get('account')
    create_time = request.POST.get('create_time')
    gender = request.POST.get('gender')
    depart = request.POST.get('depart')
    print(gender, depart)
    Department.objects.create(name=name, password=password, age=age,
                              account=account, create_time=create_time,
                              gender=gender, department_id=depart)

    return redirect("/user/list/")


class UserModelForm(forms.ModelForm):
    # name = forms.CharField(min_length=2)
    class Meta:
        model = models.UserInfo
        fields = ["name", "password", "age", "account", "create_time", "gender", "department"]
        # widgets = {
        #     "name": forms.TextInput(attrs={"class": "form-control"}),
        #     "password": forms.PasswordInput(attrs={"class": "form-control"})
        #
        # }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs = {"class": "form-control", "placeholder": field.label}


def user_model_form_add(request):
    if request.method == 'GET':
        form = UserModelForm()
        return render(request, 'user_model_form_add.html', {"form": form})
    form = UserModelForm(data=request.POST)
    if form.is_valid():
        # print(form.cleaned_data)
        form.save()
        return redirect("/user/list/")
    else:
        # print(form.errors)
        return render(request, 'user_model_form_add.html', {"form": form})


def user_edit(request, uid):
    row_object = UserInfo.objects.filter(id=uid).first()
    if request.method == 'GET':
        # 这里是ModelForm的语法，加上instance数据后，会显示这一行的数据
        form = UserModelForm(instance=row_object)
        return render(request, 'user_edit.html', {"form": form})
    # 这里不加instance（表示当前操作对象）的话，则为新增
    form = UserModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        # 如果想要向数据库添加额外数据，可以
        # form.instance.数据库字段名 = 值
        form.save()
        return redirect("/user/list/")
    else:
        # print(form.errors)
        return render(request, 'user_model_form_add.html', {"form": form})


def user_delete(request, uid):
    UserInfo.objects.filter(id=uid).delete()
    return redirect('/user/list/')


def pretty_list(request):
    data_dict = {}
    search_data = request.GET.get('num', '')
    page_num = int(request.GET.get('page', 1))
    start_num = (page_num - 1) * 10
    end_num = page_num * 10
    if search_data:
        data_dict = {'mobile__contains': search_data}
    queryset = PrettyNum.objects.filter(**data_dict).order_by("id")[start_num: end_num]
    return render(request, 'pretty_list.html', {'queryset': queryset, 'search_data': search_data})


from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError


class PrettyModelForm(forms.ModelForm):
    # 给用户提交的数据添加验证有两种方法，方法一：
    # mobile = forms.CharField(
    #     label="手机号",
    #     validators=[RegexValidator(r'^1\d{10}$', '手机号格式错误')],
    # )
    class Meta:
        model = models.PrettyNum
        # fields = "__all__" #展示数据库的所有列
        fields = ["mobile", "price", "level", "status"]
        # exclude = ['level'] #展示除了level列的所有列
        #     "name": forms.TextInput(attrs={"class": "form-control"}),
        #     "password": forms.PasswordInput(attrs={"class": "form-control"})
        #
        # }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs = {"class": "form-control", "placeholder": field.label}

    # 给用户提交的数据添加验证，方法二：
    def clean_mobile(self):
        text_mobile = self.cleaned_data['mobile']
        # 验证不通过
        # if len(text_mobile) != 11:
        #     raise ValidationError('格式错误')
        # 手机号不能重复
        exists = PrettyNum.objects.exclude(id=self.instance.pk).filter(mobile=text_mobile).exists()
        if exists:
            raise ValidationError('手机号已存在')
        # 验证通过
        return text_mobile


def pretty_add(request):
    if request.method == 'GET':
        form = PrettyModelForm()
        return render(request, 'pretty_add.html', {"form": form})
    form = PrettyModelForm(data=request.POST)
    if form.is_valid():
        # print(form.cleaned_data)
        form.save()
        return redirect("/pretty/list/")
    else:
        # print(form.errors)
        return render(request, 'pretty_add.html', {"form": form})


def pretty_edit(request, pid):
    row_object = PrettyNum.objects.filter(id=pid).first()
    if request.method == 'GET':
        # 这里是ModelForm的语法，加上instance数据后，会显示这一行的数据
        form = PrettyModelForm(instance=row_object)
        return render(request, 'pretty_edit.html', {"form": form})
    # 这里不加instance（表示当前操作对象）的话，则为新增
    form = PrettyModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        # 如果想要向数据库添加额外数据，可以
        # form.instance.数据库字段名 = 值
        form.save()
        return redirect("/pretty/list/")
    else:
        return render(request, 'pretty_edit.html', {"form": form})


def pretty_delete(request, pid):
    PrettyNum.objects.filter(id=pid).delete()
    return redirect('/pretty/list/')

djangoStudy/secondProject/app02/templates/depart_add.html
{% extends 'layout.html' %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"> 新建部门 </h3>
        </div>
        <div class="panel-body">
            <form class="form-horizontal" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label class="col-sm-2 control-label">标题</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" placeholder="标题" name="title">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary">提 交</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

djangoStudy/secondProject/app02/templates/depart_edit.html
{% extends 'layout.html' %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"> 编辑部门 </h3>
        </div>
        <div class="panel-body">
            <form class="form-horizontal" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label class="col-sm-2 control-label">标题</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" placeholder="标题" name="title" value="{{depart_info.title}}">
<!--                                <input type="hidden" class="form-control" name="id" value="{{depart_info.id}}">-->
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary">提 交</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

djangoStudy/secondProject/app02/templates/depart_list.html
{% extends 'layout.html' %}

{% block content %}
    <div style="margin-bottom: 10px">
          <!-- target="_blank" 表示打开新的tab页 -->
        <a class="btn btn-primary btn-success" href="/depart/add" target="_self"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> 新建部门</a>
      </div>
    <div class="panel panel-default">
          <!-- Default panel contents -->
          <div class="panel-heading"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
            部门列表
          </div>
          <!-- Table -->
          <table class="table">
            <thead>
              <tr>
                <th>ID</th>
                <th>名称</th>
                <th>操作</th>
              </tr>
            </thead>
            <tbody>
                {% for item in department_list %}
                   <tr>
                     <th>{{ item.id }}</th>
                     <td>{{ item.title }}</td>
                     <td>
                       <a class="btn btn-primary btn-xs" href="/depart/edit/{{item.id}}/">编辑</a>
                       <a class="btn btn-danger btn-xs" href="/depart/delete/?did={{item.id}}">删除</a>
                     </td>
                   </tr>
                {% endfor %}
            </tbody>
          </table>
      </div>
{% endblock %}

djangoStudy/secondProject/app02/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>靓号管理系统</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/dist/css/bootstrap.min.css' %}">
    <style>
      .navbar{
        border-radius: 0;
      }
    </style>
</head>
<body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">联通用户管理系统</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="/depart/list">部门管理</a></li>
            <li><a href="/user/list">用户管理 </a></li>
            <li><a href="/pretty/list">靓号管理 </a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">登录</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">个人姓名</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
</body>
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1/dist/js/bootstrap.js' %}"></script>
</html>

djangoStudy/secondProject/app02/templates/pretty_add.html
{% extends 'layout.html' %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"> 新建靓号 </h3>
        </div>
        <div class="panel-body">
            <form class="form-horizontal" method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label class="col-sm-2 control-label">{{field.label}}</label>
                        <div class="col-sm-10">
                            {{ field }}
                            <span style="color: red">{{ field.errors.0 }}</span>
                        </div>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary">提 交</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

djangoStudy/secondProject/app02/templates/pretty_edit.html
{% extends 'layout.html' %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"> 编辑靓号 </h3>
        </div>
        <div class="panel-body">
            <form class="form-horizontal" method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label class="col-sm-2 control-label">{{field.label}}</label>
                        <div class="col-sm-10">
                            {{ field }}
                            <span style="color: red">{{ field.errors.0 }}</span>
                        </div>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary">提 交</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

djangoStudy/secondProject/app02/templates/pretty_list.html
{% extends 'layout.html' %}

{% block content %}
    <div style="margin-bottom: 10px" class="clearfix">
          <!-- target="_blank" 表示打开新的tab页 -->
        <a class="btn btn-primary btn-success" href="/pretty/add" target="_self"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> 新建靓号</a>
        <div style="float: right; width:300px">
            <form method="get">
                <div class="input-group">
                   <input type="text" class="form-control" placeholder="Search for..." name="num" value="{{ search_data }}">
                   <span class="input-group-btn">
                       <button class="btn btn-default" type="submit">
                           <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                       </button>
                   </span>
                </div><!-- /input-group -->
            </form>
        </div>
    </div>
    <div class="panel panel-default">
          <!-- Default panel contents -->
          <div class="panel-heading"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
            靓号列表
          </div>
          <!-- Table -->
          <table class="table">
            <thead>
              <tr>
                <th>ID</th>
                <th>号码</th>
                <th>价格</th>
                <th>级别</th>
                <th>状态</th>
                <th>操作</th>
              </tr>
            </thead>
            <tbody>
                {% for item in queryset %}
                   <tr>
                     <th>{{ item.id }}</th>
                     <td>{{ item.mobile }}</td>
                     <td>{{ item.price }}</td>
                     <td>{{ item.get_level_display }}</td>
                     <td>{{ item.get_status_display }}</td>
                     <td>
                       <a class="btn btn-primary btn-xs" href="/pretty/edit/{{item.id}}/">编辑</a>
                       <a class="btn btn-danger btn-xs" href="/pretty/delete/{{item.id}}">删除</a>
                     </td>
                   </tr>
                {% endfor %}
            </tbody>
          </table>
    </div>
    <ul class="pagination">
        <li class="disabled"><a href="#" aria-label="Previous"><span aria-hidden="true">«</span></a></li>
        <li><a href="?page=1">1</a></li>
        <li><a href="?page=2">2</a></li>
        <li><a href="?page=3">3</a></li>
        <li><a href="?page=4">4</a></li>
        <li><a href="?page=5">5</a></li>
        <li><a href="#" aria-label="Next"><span aria-hidden="true">»</span></a></li>
    </ul>
{% endblock %}

djangoStudy/secondProject/app02/templates/test.html
{% extends 'layout.html' %}

{% block content %}
    <div style="margin-bottom: 10px">
          <!-- target="_blank" 表示打开新的tab页 -->
        <a class="btn btn-primary btn-success" href="/depart/add" target="_self"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> 新建部门</a>
      </div>
    <div class="panel panel-default">
          <!-- Default panel contents -->
          <div class="panel-heading"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
            部门列表
          </div>
          <!-- Table -->
          <table class="table">
            <thead>
              <tr>
                <th>ID</th>
                <th>名称</th>
                <th>操作</th>
              </tr>
            </thead>
            <tbody>
                {% for item in department_list %}
                   <tr>
                     <th>{{ item.id }}</th>
                     <td>{{ item.title }}</td>
                     <td>
                       <a class="btn btn-primary btn-xs" href="/depart/edit/{{item.id}}/">编辑</a>
                       <a class="btn btn-danger btn-xs" href="/depart/delete/?did={{item.id}}">删除</a>
                     </td>
                   </tr>
                {% endfor %}
            </tbody>
          </table>
      </div>
{% endblock %}

djangoStudy/secondProject/app02/templates/user_add.html
{% extends 'layout.html' %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"> 新建用户 </h3>
        </div>
        <div class="panel-body">
            <form class="form-horizontal" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label class="col-sm-2 control-label">姓名</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" placeholder="姓名" name="name">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">密码</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" placeholder="密码" name="password">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">年龄</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" placeholder="年龄" name="age">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">余额</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" placeholder="余额" name="account">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">入职时间</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" placeholder="入职时间" name="create_time">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">部门</label>
                    <div class="col-sm-10">
                       <select class="form-control" name="depart">
                            {% for item in depart_choice %}
                            <option value="{{ item.id }}">{{ item.title }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">性别</label>
                    <div class="col-sm-10">
                        <select class="form-control" name="gender">
                            {% for item in gender_choice %}
                            <option value="{{ item.0 }}">{{ item.1 }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary">提 交</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

djangoStudy/secondProject/app02/templates/user_edit.html
{% extends 'layout.html' %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"> 新建用户 </h3>
        </div>
        <div class="panel-body">
            <form class="form-horizontal" method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label class="col-sm-2 control-label">{{field.label}}</label>
                        <div class="col-sm-10">
                            {{ field }}
                            <span style="color: red">{{ field.errors.0 }}</span>
                        </div>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary">提 交</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

djangoStudy/secondProject/app02/templates/user_list.html
{% extends 'layout.html' %}

{% block content %}
    <div style="margin-bottom: 10px">
          <!-- target="_blank" 表示打开新的tab页 -->
        <a class="btn btn-primary btn-success" href="/user/add" target="_self"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> 新建用户</a>
        <a class="btn btn-primary btn-success" href="/user/model/form/add" target="_self"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> ModelForm新建用户</a>
      </div>
    <div class="panel panel-default">
          <!-- Default panel contents -->
          <div class="panel-heading"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
            用户列表
          </div>
          <!-- Table -->
          <table class="table">
            <thead>
              <tr>
                <th>ID</th>
                <th>姓名</th>
                <th>密码</th>
                <th>年龄</th>
                <th>账户余额</th>
                <th>入职时间</th>
                <th>部门</th>
                <th>性别</th>
                <th>操作</th>
              </tr>
            </thead>
            <tbody>
                {% for item in user_list %}
                   <tr>
                     <th>{{ item.id }}</th>
                     <td>{{ item.name }}</td>
                     <td>{{ item.password }}</td>
                     <td>{{ item.age }}</td>
                     <td>{{ item.account }}</td>
                     <td>{{ item.create_time|date:"Y-m-d"}}</td>
                     <td>{{ item.department.title }}</td>
                     <td>{{ item.get_gender_display }}</td>
                     <td>
                       <a class="btn btn-primary btn-xs" href="/user/edit/{{item.id}}/">编辑</a>
                       <a class="btn btn-danger btn-xs" href="/user/delete/{{item.id}}">删除</a>
                     </td>
                   </tr>
                {% endfor %}
            </tbody>
          </table>
      </div>
{% endblock %}

djangoStudy/secondProject/app02/templates/user_model_form_add.html
{% extends 'layout.html' %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"> 新建用户 </h3>
        </div>
        <div class="panel-body">
            <form class="form-horizontal" method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label class="col-sm-2 control-label">{{field.label}}</label>
                        <div class="col-sm-10">
                            {{ field }}
                            <span style="color: red">{{ field.errors.0 }}</span>
                        </div>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary">提 交</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}